name: workflow_secrets
on:
  workflow_dispatch:

env:
  DB_U: test
  DB_P: ${{ secrets.DB_PASSOWRD }}

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: check env u
        run: echo "u = ${{ env.DB_U }}"
      - name: check env p
        run: echo "u = ${{ env.DB_P }}"
